const express = require('express');
const app = express();
const PORT = process.env.PORT || 3000;
const path = require('path');
const morgan = require('morgan');
const db = require('../database/index');
const bodyParser = require('body-parser');
const multer = require('multer');
const upload = multer({ dest: './server/temp' });
const fs = require('fs');

const testData = require('../test/testData');

app.use(morgan('short'));
app.use(bodyParser.json());
app.use(express.static(path.resolve('public')));

// GET routes
app.get('/fileTree', async (req, res) => {
  let folders = await db.getAllFolders();
  folders = folders.map(folder => {
    return {
      name: folder._doc.name,
      children: [],
      type: 'folder',
      path: folder._doc.path
    }
  });
  let files = await db.getAllFiles();
  files = files.map(file => {
    return {
      name: folder._doc.name,
      children: [],
      type: 'file',
      path: file._doc.path
    }
  });
  let entities = folders.concat(files)
    .sort((a, b) => a.name - b.name)
    .map((item, index) => {
      return { ...item, id: index + 2};
    });


  let fileTree = {
    id: 1,
    name: 'root',
    children: [],
    type: 'folder',
    path: '/'
  }
  const buildTree = (root, items) => {
    items.forEach(item => {
      console.log(2, item.id);
      if(item.type === 'file') {
        root.children.push(item);
      } else {
        root.children.push(item);
        let next = root.children[root.children.length - 1];
        buildTree(next, items.filter(item => item.path === next.path + next.name));
      }
    });
  }

  console.log(1, entities)
  buildTree(fileTree, await entities);
  console.log(3, fileTree);
  res.json(testData);
});

app.get('/:folder_id', (req, res) => {
  // get all contents of a folder
})

app.get('/file/:fileID', (req, res) => {
  // lookup file metadata using fileID parameter (async)
    // if fail
      // send error response
    // else
      // request file from s3 to local storage (async)
        // if fail
          // send error response
        // else
          // rename local file to original file name from metadata
          // update metadata, incrementing numberOfDownloads
          // send download response
          // delete local file
})

// POST routes
app.post('/upload/folder', (req, res) => {
  const { name, path } = req.body;
  db.saveFolderData({ name, path }, document => {
      res.send(document);
    })
})

app.post('/upload/file', upload.single('file'), (req, res) => {
  res.json(req.file);
  // read file into storage
  // send file to s3 for storage (async)
    // if fail
      // delete local file
      // send error response
    // else
      // build metadata object with
        // file id generated by multer
        // original file name
        // path in virtual directory
        // download id from s3
      // save metadata to mongo (async)
        // if fail
          // delete local file
          // send error response
        // else
          // delete local file
          // send success response
})

app.post('/upload/files', upload.array('files'), (req, res) => {
  res.json(req.files);
})

app.listen(PORT, () => {
  console.log('App listening on port', PORT);
});